### ISSUE TITLE
Download image error: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by derodevil** [ilyalatt/Telega#76]
I want to download photo received by me. Telega generate stack trace:
   ```
at Telega.TaskWrapper.<Wrap>d__2`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telega.Client.TelegramClientUpload.<GetFileType>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramOtomax.MainUi.<GetPhoto>d__9.MoveNext() in D:\Test\Telegram\MainUi.cs:line 201
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TelegramOtomax.MainUi.<>c__DisplayClass10_0.<<Listen>b__1>d.MoveNext() in D:\Test\Telegram\MainUi.cs:line 233
```
Code to download the file and the exception was thrown here: `await tg.Upload.GetFileType(photoFileLocation);`
```
private async Task GetPhoto(TelegramClient tg, UpdatesType n)
{
	var photo = n.Default?.Updates.ElementAtOrDefault(0)?.NewMessage?.Message?.Default?.Media?.Photo?.Photo?.Default;
	if (photo == null)
		return;

	var biggestSize = photo.Sizes.Select(x => x.Default).Where(x => x != null).OrderByDescending(x => x.Size).First();
	var photoFileLocation = new InputFileLocation.PhotoTag(
			id: photo.Id,
			accessHash: photo.AccessHash,
			fileReference: photo.FileReference,
			thumbSize: biggestSize.Type);

	var fileType = await tg.Upload.GetFileType(photoFileLocation);
	var fileTypeExt = fileType.Match(
		pngTag: _ => ".png",
		jpegTag: _ => ".jpg",
		_: () => throw new NotImplementedException()
	);

	if (string.IsNullOrWhiteSpace(fileTypeExt))
		return; //not supported

	using (var fileStream = File.OpenWrite(@"D:\Test\image.jpg"))
	{
		await tg.Upload.DownloadFile(fileStream, photoFileLocation);
	}
}
```

**Comment by ilyalatt** [comment]
Hi. An interesting error. Can you attach inner exception (Collection was modified; enumeration operation may not execute) stack trace?

**Comment by derodevil** [comment]
Exception
`Telega internal exception. Unhandled exception. See an inner exception.`

Inner Exception
`Collection was modified; enumeration operation may not execute.`

Complete Exception

```
Telega.TgInternalException: Telega internal exception. Unhandled exception. See an inner exception. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Telega.Rpc.CustomObservable`1.OnNext(T value)
   at Telega.Utils.EnumerableExtensions.Iter[T](IEnumerable`1 seq, Action`1 mutator)
   at Telega.Rpc.TgTransport.<ReceiveLoopImpl>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Telega.Rpc.TgTransport.<ReceiveLoop>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Telega.Rpc.TgTransport.<>c__DisplayClass19_0`1.<<Call>g__CheckReceiveLoop|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Telega.Rpc.TgTransport.<>c__DisplayClass19_1`1.<<Call>g__AwaitResult|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telega.CallMiddleware.FloodMiddleware.<>c__DisplayClass1_1`1.<<Handle>g__ReceiveWrapper|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telega.CallMiddleware.TgCustomizedTransport.<Call>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telega.Connect.TgBellhop.<CallWithReConnect>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telega.Connect.TgBellhop.<CallWithMigration>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telega.TaskWrapper.<Wrap>d__2`1.MoveNext()
   --- End of inner exception stack trace ---
   at Telega.TaskWrapper.<Wrap>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telega.Client.TelegramClientUpload.<GetFileType>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Telegram.MainUi.<GetPhoto>d__10.MoveNext() in D:\Test\Telegram\MainUi.cs:line 284
```

**Comment by ilyalatt** [comment]
Try to use `0.5.0-preview005`. JFYI ListenToUpdates snippet is [changed a bit](https://github.com/ilyalatt/Telega/commit/1d5963377caf022ae6dfcec8b3344fa116962227#diff-0ed72552823a513d1fa052bbf1a250dd9e138397fe0abcb608b839ad8145447f).

**Comment by derodevil** [comment]
I'll try it and update if it works or not

**Comment by derodevil** [comment]
I've tested and it works. No more error. Unfortunately, the downloaded image became smaller than the original image. I took a look at the `size`
[https://ibb.co/YLfmLXG](url)

**Comment by ilyalatt** [comment]
You need to use `Progressive` tag instead of `Default`
